trigger: none # We only want this to run on PR

pr:
  branches:
    include:
      - main
      - master
      - develop
      - 'release/*'

pool:
  vmImage: 'windows-latest'

parameters:
  - name: fullAnalysis
    displayName: 'Run full analysis'
    type: boolean
    default: false

steps:
- task: PowerShell@2
  displayName: 'Analyze PR Differences'
  inputs:
    targetType: 'inline'
    script: |
      # Install jq if needed
      if (-not (Get-Command jq -ErrorAction SilentlyContinue)) {
          Write-Host "Installing jq..."
          choco install jq -y
      }

      # Set parameters
      $prId = "$(System.PullRequest.PullRequestId)"
      $org = "$(System.TeamFoundationCollectionUri)".TrimEnd('/').Split('/')[-1]
      $project = "$(System.TeamProject)"
      $repo = "$(Build.Repository.Name)"
      $pat = "$(System.AccessToken)"

      # Choose which script to run based on parameter
      if ("${{ parameters.fullAnalysis }}" -eq "true") {
          Write-Host "Running full PR analysis..."
          ./analyze-pr-diff-azdo.ps1 -PullRequestId $prId -Organization $org -Project $project -Repository $repo -PAT $pat
      } else {
          Write-Host "Running minimal PR analysis..."
          ./analyze-pr-diff-min-azdo.ps1 -PullRequestId $prId -Organization $org -Project $project -Repository $repo -PAT $pat
      }
    pwsh: true
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish PR Analysis Report'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/pr_diff_*.md'
    ArtifactName: 'PR-Analysis-Report'
    publishLocation: 'Container'
